# Generated by Django 4.2.6 on 2023-10-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address',
            field=models.TextField(default='No Address Provided'),
        ),
    ]
