# Generated by Django 4.2.6 on 2023-10-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customeraddress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='order',
            new_name='customer',
        ),
    ]
